### ISSUE TITLE
Typing plans?

### ISSUE THREAD

**Issue by mcclure** [qntm/base32768#12]
Hello. I am writing a project where I use base2048, base32768, and base65536 (all three— I give the user the choice of which they prefer). I am finding them very useful.

base2048 and base65536 have TypeScript typings, but base32768 does not. I get an error if I include base32768 in TypeScript without giving it an any-type exemption.

Are there plans to add types to base32768 like the other two have?  
If (no promises) I contributed base32768 typings by copying what the other two have, would this be a welcome PR?

Thanks.

**Comment by qntm** [comment]
I'll add typings now. I'm learning TypeScript on and off, but most of my projects don't use it yet.

**Comment by qntm** [comment]
`base32768@2.0.2` should be what you need.

**Comment by mcclure** [comment]
Confirming the update works. Thanks so much!
