### ISSUE TITLE
How To Use In Browsers Section in FAQ

### ISSUE THREAD

**Issue by jayadevanraja** [qntm/base32768#6]
It will be nice to have a FAQ Section. The question in my mind is: How to use this in a browser, like Base64? In a single file, we can have
``<img src="data:image/png;base64,iVBORw0KGgoAAA
ANSUhEUgAAAAUAAAAFCAYAAACNbyblAAAAHElEQVQI12P4
//8/w38GIAXDIBKE0DHxgljNBAAO9TXL0Y4OHwAAAABJRU
5ErkJggg==" alt="Red dot" />
``
and a red dot is displayed (example from Wikipedia). How to do this in base32768?

**Comment by qntm** [comment]
I'm not aware of any way to encode data in a data URI except by using Base64 (or plain text, if ";base64" is omitted). I don't know of any API to extend that functionality so that there could be a Base32768 data URI.

Even that were possible, I think it's unlikely to be very useful. If the web page (including the data URI) is being sent as UTF-8 text, then Base64 is more efficient than Base32768 (see the table in the README).

**Comment by jayadevanraja** [comment]
@qntm According to me, your invention - Base32768 - has extreme potential to be highly useful.

That will be useful in most cases when we need the whole document to be in a single file. This would of course mean that such documents should be encoded (or re-encoded) in UTF-16. This may be more efficient than multiple HTTP requests.

I am not an expert in this field. But probably CustomElementRegistry.define() should help.

Also @gildas-lormeau, will this be useful in [SingleFile](https://github.com/gildas-lormeau/SingleFile)?

**Comment by gildas-lormeau** [comment]
@jayadevanraja That's an interesting approach. However I think I fixed this kind of issue (e.g. optimizing the size of the saved page) by implementing [SingleFileZ](https://github.com/gildas-lormeau/SingleFileZ). I mean that it offers the best compromise today, IMHO, to store the binary resources of a web page if this problem arises.

**Comment by jayadevanraja** [comment]
I was just pointing out a potential use. Anyway, it will be good to add this into the FAQ.

**Comment by qntm** [comment]
@jayadevanraja Ah, I understand your use case now. Yes, if the web page contains a lot of inline binary data, and you are able to save it in UTF-16, then Base32768 could have some merit.

Standard techniques for packaging Node.js package for the web using existing tools like webpack or Browserify should work on the `base32768` package. But I will see if I can find time to create a Base32768 UMD which can be imported directly using a `<script>` element and accessed using `window.base32768` - if I do that, I'll add example code to the README.

**Comment by jayadevanraja** [comment]
Thanks. Any reduction in latency thus achieved would save several millions of man hours worldwide, daily.

**Comment by qntm** [comment]
@jayadevanraja `npm install base32768@2` and check out the updated README for the instructions you need for importing this package into a web browser environment. Please note that with this major version bump, the `base32768` package's `encode` and `decode` functions now accept/return `Uint8Array`s, where previously they acted on `ArrayBuffer`s.

**Comment by jayadevanraja** [comment]
Thanks. Good work.

But a layman needs some "CustomElement" defined as <img src="data:image/png;base32768,"> tag and a way to encode the binary files to base32768. Hopefully someone will some day make a product which does that, calling your library.

**Comment by qntm** [comment]
@jayadevanraja Go ahead and do it yourself!
